[SoftwareManager] Port to Python3-treq Dowloadpage() is deprecated.
Also fix crash before the port.

File '/usr/lib/enigma2/python/Plugins/SystemPlugins/SoftwareManager/plugin.py', line 764, in loadThumbnail
    client.downloadPage(thumbnailUrl, self.thumbnail).addCallback(self.setThumbnail).addErrback(self.fetchFailed)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File '/usr/lib/python3.14/site-packages/twisted/python/deprecate.py', line 302, in deprecatedFunction
  File '/usr/lib/python3.14/site-packages/twisted/web/client.py', line 858, in downloadPage
  File '/usr/lib/python3.14/site-packages/twisted/web/client.py', line 789, in _makeGetterFactory
  File '/usr/lib/python3.14/site-packages/twisted/web/_newclient.py', line 604, in _ensureValidURI
TypeError: cannot use a bytes pattern on a string-like object

Co-Authored-By: Hains van den Bosch <hainsvdbosch@ziggo.nl>